name: Android Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest # On utilise les nouveaux serveurs rapides
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          graalvm: '22.1.0.1-Final' # Le GraalVM certifié pour Android
          jdk: 'java17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'platforms;android-34 build-tools;34.0.0 ndk;26.1.10909125'

      - name: Build with Maven
        env:
          # LA LIGNE MAGIQUE : Empêche Java de planter sur les serveurs modernes
          JAVA_TOOL_OPTIONS: "-XX:-UseContainerSupport"
        run: |
          chmod +x mvnw
          ./mvnw -B -e clean gluonfx:build gluonfx:package \
            -Dgluonfx.target=android
            
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mon-application-android
          path: target/gluonfx/android/*.apk
