name: Android Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21 (GraalVM)
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      # On configure l'Android SDK AVEC le NDK avant de compiler
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'platforms;android-34 build-tools;34.0.0 ndk;26.1.10909125'

      - name: Build with Maven (Gluon)
        run: |
          chmod +x mvnw
          ./mvnw -B -e clean gluonfx:build gluonfx:package \
            -Dgluonfx.target=android \
            -Dgluonfx.force.new.capcache=true

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mon-application-android
          path: target/gluonfx/android/*.apk
