name: Android Build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Gluon's GraalVM
        uses: gluonhq/setup-graalvm@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          graalvm: '22.1.0.1-Final'
          jdk: 'java17'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'platforms;android-33 build-tools;33.0.2 ndk;25.2.9519653'

      - name: Préparer Maven
        run: chmod +x mvnw

      - name: 1. Build Native Image
        env:
          JAVA_TOOL_OPTIONS: "-XX:-UseContainerSupport"
        run: ./mvnw -B -e clean gluonfx:build -Dgluonfx.target=android

      - name: 2. Package APK
        run: |
          # 1. On force l'emplacement du dossier Android pour éviter les bugs de droits
          export ANDROID_USER_HOME=$HOME/.android
          mkdir -p $ANDROID_USER_HOME
          rm -f $ANDROID_USER_HOME/debug.keystore
          
          # 2. On génère manuellement la clé avec le format JKS (Le format que Gradle exige)
          keytool -genkey -v -keystore $ANDROID_USER_HOME/debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US" -storetype JKS
          
          # 3. On enlève le chemin parasite et on package !
          unset ANDROID_SDK_ROOT
          ./mvnw -B -e gluonfx:package -Dgluonfx.target=android
            
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: mon-application-android
          path: target/gluonfx/aarch64-android/gvm/*.apk

      - name: Upload Logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: logs-erreur
          path: target/gluonfx/aarch64-android/gvm/log/
